name: Build docker images

env:
  DOCKER_BASE_NAME: 'ghcr.io/${{ github.repository_owner }}/cert-manager-webhook-dnsimple'

on:
  workflow_call:
    inputs:
      tags:
        description: 'Multiline string of tags to build the image for'
        required: true
        type: string


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          password: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ github.repository_owner }}
      
      - name: Format tags
        id: format-tags
        # prepends the image name to each tag
        run: |
          TAGS=$(echo ${{ github.event.inputs.tags }} | awk '{print "${{ env.DOCKER_BASE_NAME }}:"$0}')
          echo "TAGS=$TAGS" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.format-tags.outputs.TAGS }}



      # currently not working
      # - name: Delete old images matching the pattern commit-*
      #   uses: snok/container-retention-policy@v2
      #   with:
      #     image-names: ${{ env.DOCKER_BASE_NAME }}/${{ env.IMAGE_NAME }}
      #     filter-tags: commit-
      #     cut-off: One month ago UTC
      #     keep-at-least: 1
      #     account-type: personal
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     token-type: github-token
