name: Build docker images

env:
  IMAGE_NAME: cert-manager-webhook-dnsimple
  DOCKER_BASE_NAME: ghcr.io/${{ github.repository_owner }}

on:
  workflow_call:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          password: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ github.repository_owner }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.DOCKER_BASE_NAME }}/${{ env.IMAGE_NAME }}:commit-${{ github.sha }}
            ${{ env.DOCKER_BASE_NAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.DOCKER_BASE_NAME }}/${{ env.IMAGE_NAME }}:${{ github.ref }}


      # currently not working
      # - name: Delete old images matching the pattern commit-*
      #   uses: snok/container-retention-policy@v2
      #   with:
      #     image-names: ${{ env.DOCKER_BASE_NAME }}/${{ env.IMAGE_NAME }}
      #     filter-tags: commit-
      #     cut-off: One month ago UTC
      #     keep-at-least: 1
      #     account-type: personal
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     token-type: github-token
