name: Build Docker Images

env:
  IMAGE_NAME: cert-manager-webhook-dnsimple
  DOCKER_BASE_NAME: ghcr.io/${{ github.repository_owner }}

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          password: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ github.repository_owner }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.DOCKER_BASE_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.DOCKER_BASE_NAME }}/${{ env.IMAGE_NAME }}:latest
