name: Run tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  
jobs:
  code-test:
    name: Run tests on code
    uses: ./.github/actions/run-code-tests.yaml
  
  build-image:
    name: Build Docker image
    uses: ./.github/actions/build-images.yaml
    # needs: code-test

  webhook-tests:
    name: Run tests on webhooks
    uses: ./.github/actions/run-webhook-tests.yaml
    needs: build-image
