name: Run code tests

on:
  push:
  workflow_call:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.x'
        cache-dependency-path: src/go.mod


    - name: Install kubebuilder fixtures
      id: kubebuilder
      run: |
        go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
        echo "BIN_DIR=$(setup-envtest use -p path)" >> $GITHUB_OUTPUT


    - name: Run tests
      run: |
        export TEST_ASSET_KUBE_APISERVER=${{ steps.kubebuilder.outputs.BIN_DIR }}/kube-apiserver
        export TEST_ASSET_ETCD=${{ steps.kubebuilder.outputs.BIN_DIR }}/etcd
        export TEST_ASSET_KUBECTL=${{ steps.kubebuilder.outputs.BIN_DIR }}/kubectl
        export TEST_ZONE_NAME=puzzzzle.ch.
        export DNSIMPLE_SANDBOX=true
        echo """apiVersion: v1
        kind: Secret
        metadata:
          name: dnsimple-token
        type: Opaque
        data:
            token: $(echo -n '${{ secrets.DNSIMPLE_API_TOKEN }}' | base64)
        """ > testdata/dnsimple-token.yaml
        cd src
        go test -v .
