name: Run code tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.x'
  
    - name: Change directory
      run: cd src

    - name: Install dependencies
      run: go get .

    - name: Run tests
      run: go test -v .
