name: Run code tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.x'
  
    - name: Run tests
      run: cd src && go test -v .
