name: Run PR tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  
jobs:
  code-test:
    name: Run tests on code
    uses: ./.github/workflows/run-code-tests.yaml
  
  build-image:
    name: Build Docker image
    uses: ./.github/workflows/build-images.yaml
    with:
      tags: >
        commit-${{ github.sha }}
        latest
    # needs: code-test

  webhook-tests:
    name: Run tests on webhooks
    needs: build-image
    uses: ./.github/workflows/run-kubernetes-tests.yaml
