name: Publish new release

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  docker-build:
    name: Build tagged Docker image
    uses: ./.github/workflows/build-images.yaml

  webhook-tests:
    name: Release new helm chart version
    uses: ./.github/workflows/chart-release.yaml
    needs: docker-build
